### ISSUE TITLE
Vuetify 2 Breakpoints not working

### ISSUE THREAD

**Issue by GuillaumeBec** [Shinigami92/vite-pug-error-repro#1]
Hello there ! 

I'm trying to migrate my project from Vue CLI to Vite, with Vuetify 2 version.  I've encountered a problem with Vuetify Media queries that block builds (prod and dev). 

Re-starting  my work from your starter, i've encountered the same issue. 

Trying a media query in you App.vue  :

```
<template>
  <h1>hello world</h1>
</template>

<script lang="ts">
import logo from '@/assets/logo.png';
import { defineComponent } from '@vue/composition-api';

export default defineComponent({
  name: 'App',
  setup() {
    return { logo };
  },
  created() {
    console.log(logo);
  }
});
</script>
<style lang="scss" scoped>
@media #{map-get($display-breakpoints, 'sm-and-down')} {
  h1 {
    color: red;
  }
}
</style>
```

Made me run into : 

![Screenshot 2022-07-01 at 16 38 10](https://user-images.githubusercontent.com/59207874/176915624-a898ff8e-224f-47b3-920b-f4bb9471209d.png)

Just in case, i've set my sass loading modules to these versions : 
  ```  "sass": "^1.19.0",
    "sass-loader": "^8.0.0"

**Comment by Shinigami92** [comment]
Please note that this was just a repo for a reproduction for a github issue
I sadly don't know anymore the github issue and also don't know anymore what this issue was about
It's to far in the past
This is not a starter template as you thought
I also don't work nowadays with vueitfy anymore and moved to Quasar, so I cannot help you with any related issues

Please open an issue in the related repo where you have the bug with
I will set this repo to archived
